// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBi6Qg4SWEzlZwUa1ThWErPOCM2YeAtS0',
    appId: '1:537763234730:web:6ec111ad23470d9668e1d3',
    messagingSenderId: '537763234730',
    projectId: 'subdiserve-1cd42',
    authDomain: 'subdiserve-1cd42.firebaseapp.com',
    storageBucket: 'subdiserve-1cd42.firebasestorage.app',
    measurementId: 'G-FYQLT7DYYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPefZIvlNs1lpU-Liq95G-kw2PnRPck90',
    appId: '1:537763234730:android:0cd133dc56be8c4768e1d3',
    messagingSenderId: '537763234730',
    projectId: 'subdiserve-1cd42',
    storageBucket: 'subdiserve-1cd42.firebasestorage.app',
  );
}
